### PR TITLE
CentOS 8 for ARM

### PR DESCRIPTION
**Pull request by scopatz**
As per title. CC @isuruf @jakirkham

### CODE REVIEW

**Comment by scopatz** [comment]
For https://github.com/conda-forge/cudatoolkit-feedstock/pull/4

**Comment by jakirkham** [comment]
I think we will want an NVIDIA based image like we have on `x86_64` and `ppc64le` so that we can get the dev tools as well. The image name is [`nvidia/cuda-arm64`]( https://hub.docker.com/r/nvidia/cuda-arm64/tags ). These were only added recently. So we only have CUDA 11.0+ support.

**Comment by scopatz** [comment]
OK, yeah, I think I am less interested in doing that right now. I'll leave this here for others to take a look or take over if they want.

**Comment by jakirkham** [comment]
cc @JasonAtNvidia (for vis)

**Comment by jakirkham** [comment]
The underlying use case was addressed by PR ( https://github.com/conda-forge/docker-images/pull/189 )

**Comment by jakirkham** [comment]
Thanks for the work here Anthony! 😄

**Pull request closed without merging**
