### PR TITLE
Use our patch

### PR DESCRIPTION
**Pull request by jakirkham**
Drops `patch` from the system and installs it with Conda instead.

Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jakirkham** [comment]
cc @conda-forge/core

**Comment by isuruf** [comment]
Any reason to do this? Merging this PR means patch has to be built as a conda package when bootstrapping a new architecture

**Comment by jakirkham** [comment]
Generally to cut down on our reliance on system dependencies (as we did with `git` previously).

We will do that anyways. ( https://github.com/conda-forge/patch-feedstock )

**Comment by isuruf** [comment]
> We will do that anyways. ( https://github.com/conda-forge/patch-feedstock )

My point is that, we can't use the conda-forge infrastructure to build `patch` when bootstrapping a new architecture if the docker image relies on a conda `patch` package.

**Comment by jakirkham** [comment]
Again this is no different than anything else in that list (like `git`). Besides people can still use `yum_requirements.txt` to workaround things that are not in that list (as they do easily today).

**Comment by isuruf** [comment]
Everything else are conda-build requirements, which we have to build anyway on a new architecture. I believe the same argument was raised in https://github.com/conda-forge/docker-images/pull/12#issuecomment-222979390 about bootstrapping.

**Comment by scopatz** [comment]
I am in favor of this

**Comment by jakirkham** [comment]
CI failures are now cleared thanks to PR ( https://github.com/conda-forge/docker-images/pull/96 ).

**Comment by jakirkham** [comment]
@conda-forge/core, any other thoughts on this?

**Comment by scopatz** [comment]
I think the bootstrapping problems will always be there, and rejecting this PR doesn't change that.  I am going to merge.  If @isuruf or others have concerns remaining, we can revert if needed.

**Pull request merged**
