### PR TITLE
Install qemu in linux-anvil-cuda

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by isuruf** [comment]
cc @leofang

**Review by leofang — APPROVED** [review]
Thanks, Isuru!

**Comment by leofang** [comment]
cc: @jakirkham @kkraus14 for vis

**Review by kkraus14 — APPROVED** [review]

**Comment by leofang** [comment]
It seems `linux-anvil-ppc64le-cuda:11.2` still does not go through on main...?

**Pull request merged**
