### PR TITLE
Switch to BSD 3-Clause license

### PR DESCRIPTION
**Pull request by jakirkham**
Fixes https://github.com/conda-forge/docker-images/issues/40

cc @conda-forge/core

### CODE REVIEW

**Comment by jakirkham** [comment]
The build failure seen here will be fixed by PR ( https://github.com/conda-forge/docker-images/pull/44 ).

**Comment by jakirkham** [comment]
Toggling to restart CI.

**Comment by jakirkham** [comment]
Now passing. 😄

**Comment by jakirkham** [comment]
Friendly nudge @conda-forge/core.

**Comment by scopatz** [comment]
LGTM but again  no push rights here :)

**Comment by jakirkham** [comment]
We need to actually have a team for the docker image. Right now there's a list on the repo itself, which is a bit ridiculous. 😜

**Comment by jjhelmus** [comment]
I have merge right!

**Pull request merged**
