### PR TITLE
add mambaforge

### LINKED ISSUE #168: Add mambaforge image
now that we also have `mambaforge`, it would be great to add a docker image to the docker hub.

The Dockerfile is the same of `miniforge`, replacing the name with `mamabaforge`.

### PR DESCRIPTION
**Pull request by jaimergp**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Will close #168

### CODE REVIEW

**Comment by jaimergp** [comment]
@conda-forge/core this is ready for review!

**Review by xhochy — APPROVED** [review]

**Comment by xhochy** [comment]
Thanks 🎉

**Comment by wolfv** [comment]
awesome! :tada:

**Comment by jaimergp** [comment]
Yay! 🚀

**Pull request merged**
