### PR TITLE
ENH add readme and other docs

### PR DESCRIPTION
**Pull request by beckermr**
This PR adds readmes, descriptions, and pushes them places.

### CODE REVIEW

**Comment by jakirkham** [comment]
Thanks Matt! 🙏

Should we take this for a spin? Or is there more that you were wanting to do here?

**Comment by beckermr** [comment]
I need to add readmee or code to make them.

**Comment by jakirkham** [comment]
Gotcha. Would it be worth testing with the README of the repo? Or a simple stub README? That way we could iron out any technical kinks

Then we could handle filling out the README(s) further as a follow up task

**Comment by beckermr** [comment]
Sure if you want to.

**Comment by beckermr** [comment]
OK @jakirkham this one is ready to go in as a test. Once we confirm the readmes are showing up on dockerhub and quay, we can go back and generate actual content for them.

**Comment by jakirkham** [comment]
Sounds good. Let's take this for a spin. Thanks Matt! 🙏

**Comment by jakirkham** [comment]
Looks like we are seeing errors. Taken from [one CI job]( https://github.com/conda-forge/docker-images/actions/runs/8302900526/job/22726075250#step:12:17 ):

Missing CSRF token?

```
level=debug msg="root cmd init config"
level=debug msg="home dir: /github/home"
level=debug msg="subcommand \"pushrm\" called"
level=debug msg="Using target: quay.io/condaforge/linux-anvil-cos7-x86_64:latest"
level=debug msg="using README file: linux-anvil-cos7-x86_64/README.md"
level=debug msg="server: quay.io"
level=debug msg="namespace: condaforge"
level=debug msg="repo: linux-anvil-cos7-x86_64"
level=debug msg="tag: latest"
level=debug msg="repo provider: quay"
level=debug msg="Quay.GetAuthident called"
level=debug msg="Using Docker creds:  ********"
level=debug msg="Quay.Pushrm called"
level=debug msg="util.GetApikey called"
level=debug msg="apikey: ********"
level=debug msg="push readme, response body: {\"error\": \"CSRF token was invalid or missing.\"}"
level=debug msg="push README, status code: 403"
level=debug msg="error pushing README, bad status code for response: 403 Forbidden. Try \"docker logout\" and \"docker login\""
level=error msg="error pushing readme to repo server. See error message below. Run with \"--debug\" for more details. \n\nerror pushing README, bad status code for response: 403 Forbidden. Try \"docker logout\" and \"docker login\""
```

**Comment by beckermr** [comment]
We must not have the right quay.io api key.

**Comment by jakirkham** [comment]
Apparently there is a particular way we need to generate the key: https://github.com/christian-korneck/docker-pushrm/issues/13#issuecomment-748509557

**Comment by beckermr** [comment]
ok did that and trying again

**Comment by jakirkham** [comment]
Thanks Matt! Looks great 🤩

Screenshot 2024-03-15 at 5 44 02 PM

**Comment by jakirkham** [comment]
Noting the key addition for posterity

xref: https://github.com/conda-forge/docker-images/commit/cd4c5d3814789aa13fc2d1e7526e75ef49295539

**Comment by beckermr** [comment]
Awesome. I'll try and push code to generate a proper readme for each image in the next few days.

**Comment by jakirkham** [comment]
Sounds good. Am happy to help. We may be able to share this work amongst contributors as well

Thinking we can probably use one templated README and apply that to different images

**Pull request merged**
