### PR TITLE
Update to Mambaforge 4.14.0-1

### PR DESCRIPTION
**Pull request by jakirkham**
xref: https://github.com/conda-forge/miniforge/pull/358

cc @hmaarrfk @jaimergp

### CODE REVIEW

**Comment by jakirkham** [comment]
Strange `su-exec` and `tini` have no dependencies outside of compiler runtime libraries

**Comment by jaimergp** [comment]
I am going to check locally to see where that error comes from, maybe a red herring.

**Comment by jakirkham** [comment]
Thanks Jaime 🙏

Went ahead and pushed a commit to test on CI without those. Though it may require more debugging than that

**Comment by jaimergp** [comment]
`curl`'s pin looks wrong. 

7.83.0 packages for libcurl only have two variants:

* [linux-aarch64/libcurl-7.83.0-h8fd98b7_0.tar.bz2](https://anaconda.org/conda-forge/libcurl/7.83.0/download/linux-aarch64/libcurl-7.83.0-h8fd98b7_0.tar.bz2)
* [linux-aarch64/libcurl-7.83.0-h22f3f83_0.tar.bz2](https://anaconda.org/conda-forge/libcurl/7.83.0/download/linux-aarch64/libcurl-7.83.0-h22f3f83_0.tar.bz2)

But `curl` wants `libcurl 7.83.0 h13c8431_0`, which is not a hash I can find there. 🤔

**Comment by jaimergp** [comment]
Well, this solves locally:

```
$ CONDA_SUBDIR=linux-aarch64 mamba create -n unused --dry-run --yes --quiet python=3.10 git patch pip conda-build boa anaconda-client su-exec tini mamba=0.27 conda=4.14 pip

  Package                               Version  Build               Channel                         Size
───────────────────────────────────────────────────────────────────────────────────────────────────────────
  Install:
───────────────────────────────────────────────────────────────────────────────────────────────────────────

  + _openmp_mutex                           4.5  2_gnu               conda-forge/linux-aarch64       24kB
  + anaconda-client                       1.8.0  pyhd8ed1ab_0        conda-forge/noarch            Cached
  + anyio                                 3.6.1  pyhd8ed1ab_1        conda-forge/noarch            Cached
  + attrs                                22.1.0  pyh71513ae_1        conda-forge/noarch            Cached
  + backports                               1.0  py_2                conda-forge/noarch            Cached
  + backports.functools_lru_cache         1.6.4  pyhd8ed1ab_0        conda-forge/noarch            Cached
  + beautifulsoup4                       4.11.1  pyha770c72_0        conda-forge/noarch            Cached
  + boa                                  0.12.0  pyha770c72_4        conda-forge/noarch              57kB
  + brotlipy                              0.7.0  py310h761cc84_1004  conda-forge/linux-aarch64      361kB
  + bzip2                                 1.0.8  hf897c2e_4          conda-forge/linux-aarch64      405kB
  + c-ares                               1.18.1  hf897c2e_0          conda-forge/linux-aarch64      121kB
  + ca-certificates                   2022.9.24  h4fd8a4c_0          conda-forge/linux-aarch64      154kB
  + certifi                           2022.9.24  pyhd8ed1ab_0        conda-forge/noarch            Cached
  + cffi                                 1.15.1  py310hf0c4615_0     conda-forge/linux-aarch64      260kB
  + chardet                               5.0.0  py310hbbe02a8_0     conda-forge/linux-aarch64      266kB
  + charset-normalizer                    2.1.1  pyhd8ed1ab_0        conda-forge/noarch            Cached
  + clyent                                1.2.2  py_1                conda-forge/noarch            Cached
  + colorama                              0.4.5  pyhd8ed1ab_0        conda-forge/noarch            Cached
  + commonmark                            0.9.1  py_0                conda-forge/noarch            Cached
  + conda                                4.14.0  py310h4c7bcd0_0     conda-forge/linux-aarch64        1MB
  + conda-build                          3.22.0  py310h4c7bcd0_2     conda-forge/linux-aarch64      588kB
  + conda-package-handling                1.9.0  py310h761cc84_0     conda-forge/linux-aarch64        1MB
  + cryptography                         38.0.1  py310h07dd38e_0     conda-forge/linux-aarch64        2MB
  + curl                                 7.85.0  h8fd98b7_0          conda-forge/linux-aarch64       96kB
  + dataclasses                             0.8  pyhc8e2a94_3        conda-forge/noarch            Cached
  + expat                                 2.4.9  ha18d298_0          conda-forge/linux-aarch64      167kB
  + filelock                              3.8.0  pyhd8ed1ab_0        conda-forge/noarch            Cached
  + future                               0.18.2  py310hbbe02a8_5     conda-forge/linux-aarch64      756kB
  + gettext                            0.19.8.1  h4de3ea5_1009       conda-forge/linux-aarch64        4MB
  + git                                  2.38.0  pl5321h6429092_0    conda-forge/linux-aarch64       21MB
  + glob2                                   0.7  py_0                conda-forge/noarch            Cached
  + icu                                    70.1  ha18d298_0          conda-forge/linux-aarch64       14MB
  + idna                                    3.4  pyhd8ed1ab_0        conda-forge/noarch            Cached
  + importlib-metadata                   4.11.4  py310hbbe02a8_0     conda-forge/linux-aarch64       34kB
  + importlib_resources                   5.9.0  pyhd8ed1ab_0        conda-forge/noarch            Cached
  + jinja2                                3.1.2  pyhd8ed1ab_1        conda-forge/noarch            Cached
  + joblib                                1.2.0  pyhd8ed1ab_0        conda-forge/noarch             210kB
  + json5                                 0.9.5  pyh9f0ad1d_0        conda-forge/noarch            Cached
  + jsonschema                           4.16.0  pyhd8ed1ab_0        conda-forge/noarch            Cached
  + jupyter_core                         4.11.1  py310h4c7bcd0_0     conda-forge/linux-aarch64       84kB
  + keyutils                              1.6.1  h4e544f5_0          conda-forge/linux-aarch64      112kB
  + krb5                                 1.19.3  h7c456eb_0          conda-forge/linux-aarch64        2MB
  + ld_impl_linux-aarch64                2.36.1  h02ad14f_2          conda-forge/linux-aarch64      685kB
  + libarchive                            3.5.2  h610d84a_3          conda-forge/linux-aarch64        2MB
  + libcurl                              7.85.0  h8fd98b7_0          conda-forge/linux-aarch64      367kB
  + libedit                        3.1.20191231  he28a2e2_2          conda-forge/linux-aarch64      134kB
  + libev                                  4.33  h516909a_1          conda-forge/linux-aarch64      106kB
  + libffi                                3.4.2  h3557bc0_5          conda-forge/linux-aarch64       59kB
  + libgcc-ng                            12.1.0  h3242a24_16         conda-forge/linux-aarch64      543kB
  + libgomp                              12.1.0  h3242a24_16         conda-forge/linux-aarch64      467kB
  + libiconv                               1.17  h9cdd2b7_0          conda-forge/linux-aarch64        1MB
  + liblief                              0.12.2  h4de3ea5_0          conda-forge/linux-aarch64        2MB
  + libmamba                             0.27.0  hfcbcd16_0          conda-forge/linux-aarch64        2MB
  + libmambapy                           0.27.0  py310h76fea7e_0     conda-forge/linux-aarch64      334kB
  + libnghttp2                           1.47.0  h4173d3e_1          conda-forge/linux-aarch64      944kB
  + libnsl                                2.0.0  hf897c2e_0          conda-forge/linux-aarch64       32kB
  + libsolv                              0.7.22  h7866ba4_0          conda-forge/linux-aarch64      466kB
  + libsqlite                            3.39.4  hf9034f9_0          conda-forge/linux-aarch64        1MB
  + libssh2                              1.10.0  h4bb3959_3          conda-forge/linux-aarch64      248kB
  + libstdcxx-ng                         12.1.0  hd01590b_16         conda-forge/linux-aarch64        4MB
  + libuuid                              2.32.1  hf897c2e_1000       conda-forge/linux-aarch64       31kB
  + libxml2                              2.10.2  hd2439e0_1          conda-forge/linux-aarch64      806kB
  + libzlib                              1.2.12  h4e544f5_4          conda-forge/linux-aarch64       75kB
  + lz4-c                                 1.9.3  h01db608_1          conda-forge/linux-aarch64      204kB
  + lzo                                    2.10  h516909a_1000       conda-forge/linux-aarch64      283kB
  + mamba                                0.27.0  py310hcf12e44_0     conda-forge/linux-aarch64       46kB
  + markupsafe                            2.1.1  py310hdc54845_1     conda-forge/linux-aarch64       23kB
  + nbformat                              5.6.1  pyhd8ed1ab_0        conda-forge/noarch             109kB
  + ncurses                                 6.3  headf329_1          conda-forge/linux-aarch64        1MB
  + openssl                              1.1.1q  h4e544f5_0          conda-forge/linux-aarch64        2MB
  + patch                                 2.7.6  hf897c2e_1002       conda-forge/linux-aarch64      133kB
  + patchelf                             0.15.0  h884eca8_0          conda-forge/linux-aarch64      106kB
  + pcre2                                 10.37  he7b27c6_1          conda-forge/linux-aarch64        1MB
  + perl                                 5.32.1  2_hf897c2e_perl5    conda-forge/linux-aarch64       15MB
  + pip                                  22.2.2  pyhd8ed1ab_0        conda-forge/noarch            Cached
  + pkginfo                               1.8.3  pyhd8ed1ab_0        conda-forge/noarch            Cached
  + pkgutil-resolve-name                 1.3.10  pyhd8ed1ab_0        conda-forge/noarch            Cached
  + prompt-toolkit                       3.0.31  pyha770c72_0        conda-forge/noarch            Cached
  + prompt_toolkit                       3.0.31  hd8ed1ab_0          conda-forge/noarch            Cached
  + psutil                                5.9.2  py310h761cc84_0     conda-forge/linux-aarch64      362kB
  + py-lief                              0.12.2  py310h130cc07_0     conda-forge/linux-aarch64        2MB
  + pybind11-abi                              4  hd8ed1ab_3          conda-forge/noarch            Cached
  + pycosat                               0.6.3  py310h761cc84_1010  conda-forge/linux-aarch64      111kB
  + pycparser                              2.21  pyhd8ed1ab_0        conda-forge/noarch            Cached
  + pygments                             2.13.0  pyhd8ed1ab_0        conda-forge/noarch            Cached
  + pyopenssl                            22.0.0  pyhd8ed1ab_1        conda-forge/noarch            Cached
  + pyrsistent                           0.18.1  py310hdc54845_1     conda-forge/linux-aarch64       95kB
  + pysocks                               1.7.1  pyha2e5f31_6        conda-forge/noarch            Cached
  + python                               3.10.6  h023d47c_0_cpython  conda-forge/linux-aarch64       14MB
  + python-dateutil                       2.8.2  pyhd8ed1ab_0        conda-forge/noarch            Cached
  + python-fastjsonschema                2.16.2  pyhd8ed1ab_0        conda-forge/noarch             247kB
  + python-libarchive-c                     4.0  py310h4c7bcd0_1     conda-forge/linux-aarch64       64kB
  + python_abi                             3.10  2_cp310             conda-forge/linux-aarch64        4kB
  + pytz                                 2022.4  pyhd8ed1ab_0        conda-forge/noarch            Cached
  + pyyaml                                  6.0  py310h761cc84_4     conda-forge/linux-aarch64      176kB
  + readline                              8.1.2  h38e3740_0          conda-forge/linux-aarch64      312kB
  + reproc                               14.2.3  hf897c2e_0          conda-forge/linux-aarch64       30kB
  + reproc-cpp                           14.2.3  h01db608_0          conda-forge/linux-aarch64       20kB
  + requests                             2.28.1  pyhd8ed1ab_1        conda-forge/noarch            Cached
  + rich                                 12.6.0  pyhd8ed1ab_0        conda-forge/noarch            Cached
  + ripgrep                              13.0.0  hc770f70_2          conda-forge/linux-aarch64        2MB
  + ruamel.yaml                         0.17.21  py310h761cc84_1     conda-forge/linux-aarch64      179kB
  + ruamel.yaml.clib                      0.2.6  py310h761cc84_1     conda-forge/linux-aarch64      146kB
  + ruamel_yaml                         0.15.80  py310h761cc84_1007  conda-forge/linux-aarch64      253kB
  + setuptools                           65.4.1  pyhd8ed1ab_0        conda-forge/noarch            Cached
  + six                                  1.16.0  pyh6c4a22f_0        conda-forge/noarch            Cached
  + sniffio                               1.3.0  pyhd8ed1ab_0        conda-forge/noarch              14kB
  + soupsieve                       2.3.2.post1  pyhd8ed1ab_0        conda-forge/noarch            Cached
  + su-exec                                 0.2  h516909a_1002       conda-forge/linux-aarch64        9kB
  + tini                                 0.19.0  hf897c2e_0          conda-forge/linux-aarch64       14kB
  + tk                                   8.6.12  hd8af866_0          conda-forge/linux-aarch64        4MB
  + toml                                 0.10.2  pyhd8ed1ab_0        conda-forge/noarch            Cached
  + toolz                                0.12.0  pyhd8ed1ab_0        conda-forge/noarch            Cached
  + tqdm                                 4.64.1  pyhd8ed1ab_0        conda-forge/noarch            Cached
  + traitlets                             5.4.0  pyhd8ed1ab_0        conda-forge/noarch            Cached
  + typing_extensions                     4.3.0  pyha770c72_0        conda-forge/noarch            Cached
  + tzdata                                2022d  h191b570_0          conda-forge/noarch            Cached
  + urllib3                             1.26.11  pyhd8ed1ab_0        conda-forge/noarch            Cached
  + watchgod                              0.8.2  pyhd8ed1ab_0        conda-forge/noarch              15kB
  + wcwidth                               0.2.5  pyh9f0ad1d_2        conda-forge/noarch            Cached
  + wheel                                0.37.1  pyhd8ed1ab_0        conda-forge/noarch            Cached
  + xz                                    5.2.6  h9cdd2b7_0          conda-forge/linux-aarch64      441kB
  + yaml                                  0.2.5  hf897c2e_2          conda-forge/linux-aarch64       93kB
  + yaml-cpp                              0.7.0  h4de3ea5_2          conda-forge/linux-aarch64      211kB
  + zipp                                  3.8.1  pyhd8ed1ab_0        conda-forge/noarch            Cached
  + zstd                                  1.5.2  hc1e27d5_4          conda-forge/linux-aarch64      458kB

  Summary:

  Install: 126 packages

  Total download: 112MB
```

So it _should_ work on CI too? What if we remove the `update --all` command to check?

**Comment by jakirkham** [comment]
It doesn't look like this issue is showing up on CI. Maybe we should rebuild `su-exec` & `tini` and retry?

* https://github.com/conda-forge/su-exec-feedstock/pull/9
* https://github.com/conda-forge/tini-feedstock/pull/17

**Comment by jaimergp** [comment]
I cannot reproduce locally even if I do it step by step, with the same versions and everything, so no clue what's going on :/

**Comment by jakirkham** [comment]
Very odd 🤔 Thanks for debugging Jaime 😄

Well let's try rebuilding both packages and then rerun CI here. If it is gone, great. If not, we can debug further. Maybe it is possible to `ssh` into GHA to debug the failed job directly?

**Comment by jaimergp** [comment]
Yes, with an action like this one: https://github.com/marketplace/actions/debugging-with-ssh

**Comment by jakirkham** [comment]
Ok those have been rebuilt. So retrying 🍀

**Comment by jaimergp** [comment]
Looks like that worked! 🤞

**Comment by jakirkham** [comment]
Woot! 🎉

Looks like the release is still marked as a pre-release upstream. Also seeing this PR comment ( https://github.com/conda-forge/miniforge/pull/358#discussion_r989842505 ). So leaving as draft until we hear back on those, but sounds like we should be good to go once those are done.

**Comment by hmaarrfk** [comment]
I still can't get some packages to resolve, and pypy + ppc64le is taking a really long itme...

**Comment by jakirkham** [comment]
Was that comment intended for this thread ( https://github.com/conda-forge/miniforge/pull/358#discussion_r989842505 )?

**Comment by hmaarrfk** [comment]
A little bit of both. I think you two go to the bottom of some inconsistencies. I'm somewhat trying to pull more interested parties.

**Comment by jakirkham** [comment]
Superseded by PR ( https://github.com/conda-forge/docker-images/pull/224 )

**Pull request closed without merging**
