### PR TITLE
Stop python downgrade

### PR DESCRIPTION
**Pull request by isuruf**
So that the installation is not upgraded to python 3.7

### CODE REVIEW

**Comment by jakirkham** [comment]
Maybe we should pin the Python version as well?

**Comment by jakirkham** [comment]
Thoughts?

**Comment by jakirkham** [comment]
Added PR ( https://github.com/conda-forge/docker-images/pull/75 ) to try solving this another way.

**Comment by scopatz** [comment]
I am in favor of this.

**Comment by isuruf** [comment]
Ready for review again

**Pull request merged**
