### PR TITLE
Make sure the alma images have different names

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jakirkham** [comment]
The original idea here was to use a multiarch image. It's possible there's some else still need to make that work well. Am happy to take a look if needed

**Comment by isuruf** [comment]
It doesn't work at the moment. We only use the docker image name in conda-smithy and just saying `linux-anvil-alma` would bring in arm64 image on a x86_64 runner. Also when emulating the full system, we need to be able to say we need the ppc64le docker image on the x86_64 runner which is not possible right now as well.

**Comment by xhochy** [comment]
This could be done by also passing in the `--platform` switch on `docker run` to select the underlying architecture but this didn't work well for me in the past. It often fell back to the native architecture when I had selected a non-native/emulated one. Using the `sha256` digest works reliably to select non-native platforms but I don't see a way to transfer that easily into our build scripts.

Thus I'm also in favour of this PR as it keeps the images easily distinguishable and works very reliable in selecting the execution architecture.

**Comment by isuruf** [comment]
Ping on this @jakirkham

**Comment by isuruf** [comment]
Ping

**Pull request merged**
