### PR TITLE
Use Miniconda 4.5.4

### PR DESCRIPTION
**Pull request by jakirkham**
Make use of Miniconda 4.5.4. Also update the activation steps to reflect the preferred strategy after conda 4.4.0+.

### CODE REVIEW

**Comment by scopatz** [comment]
Seeing the error:

```
Step 9/13 : RUN /opt/docker/bin/run_commands
 ---> Running in 13fb8f250ce8
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
bash: conda: command not found
bash: conda: command not found
chgrp: cannot access `/opt/conda': No such file or directory
The command '/bin/sh -c /opt/docker/bin/run_commands' returned a non-zero code
```

**Comment by jakirkham** [comment]
Yeah, me too. Looking into it.

**Comment by jakirkham** [comment]
Added PR ( https://github.com/conda-forge/docker-images/pull/71 ) to improve debugging. It's not totally clear from `docker build` what went wrong, but that appears necessary to figure it out.

**Comment by jakirkham** [comment]
Pushed something that fixed it for me locally. Also tried running the image. Created a simple `conda` environment with some stuff and activated it to make sure it was working correctly.

**Pull request merged**
