### PR TITLE
Fix downloading yum repos

### PR DESCRIPTION
**Pull request by isuruf**
Fixes https://github.com/conda-forge/docker-images/issues/165

### CODE REVIEW

**Comment by isuruf** [comment]
@conda-forge/core, this is ready. We can discuss dropping centos 6 later, but this is needed to fix recipes using `yum_requirements.txt`.

**Review by ocefpaf — APPROVED** [review]

**Comment by jakirkham** [comment]
Thanks! 😄

**Comment by hmaarrfk** [comment]
Thanks for the quick turnaround!

**Comment by mrakitin** [comment]
Thanks @isuruf! It's a great fix for nsls2forge too!

**Pull request merged**
