### PR TITLE
Consolidate cos7 and alma8 docker files

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by isuruf** [comment]
@conda-forge/core, this is ready

**Comment by jakirkham** [comment]
When it comes to distributions, think it is better to keep them in separate `Dockerfile`s

For example this is now adding CentOS 7 repos to Alma, which don't make sense there. Plus the naming of the directories is confusing

If the goal is simply to consolidate more content, would suggest taking the `yum` step changed here and moving it into a script that all images call

**Comment by isuruf** [comment]
> For example this is now adding CentOS 7 repos to Alma, which don't make sense there. Plus the naming of the directories is confusing

We are not. The fix_rpm uses those repos only for centos7. We would have to add alma8 repos there in the future as well.

This PR reduces code duplication and the only thing that this PR does more is to copy centos7 repos and delete them without using them in alma8 which is okay IMO.

**Review by h-vetinari — APPROVED** [review]
I like the deduplication. Also, both images are RHEL-derivatives, so _a lot_ is the same, and the differences are small enough that unification is beneficial IMO.

**Comment by isuruf** [comment]
@jakirkham let me know if there are any other objections.

**Comment by h-vetinari** [comment]
As a great illustration why this PR is beneficial, the [addition](https://github.com/conda-forge/docker-images/pull/290) of alma9-based images becomes absolutely trivial.

**Comment by h-vetinari** [comment]
Ping @jakirkham

**Comment by h-vetinari** [comment]
@jakirkham, it's been 3 weeks since you requested changes here. Please either engage in the discussion or lift your objection. 

It's completely fine to disagree, but blocking something and then not responding anymore is not OK.[^1]  Let's please figure out what our respective concerns / constraints are, and find a mutually satisfactory solution.

[^1]: You reviewed another PR here in the meantime (less than 2h after it opened...), so it's hard to believe that you missed all the pings in between.

**Pull request merged**
