### PR TITLE
DOC: Fix typo

### PR DESCRIPTION
**Pull request by jakirkham**
Fixes a typo in the README.

### CODE REVIEW

**Comment by ocefpaf** [comment]
:scream:

**Comment by jakirkham** [comment]
No worries.

**Comment by jakirkham** [comment]
Any chance I could get commit permissions on this?

**Comment by ocefpaf** [comment]
You don't? That is weird...

**Comment by jakirkham** [comment]
Yeah, I didn't see the merge button for that PR. Should this have already happened? Looks like you have fixed it now.

Basically, I think I have permissions on most things that I tend to be involved with staged-recipes, conda-forge.github.io, and anything I am a maintainer on. Though I don't have permissions on this, conda-smithy, or any feedstock I am not a maintainer on.

With things I am not a maintainer on, it can be kind of annoying when doing a maintenance PRs to have to wait for someone else to merge them (e.g. re-rendering, switching compilers, or similar), but it's not a big deal as I don't want the SNR of notifications to plummet. With conda-smithy, basically without getting both you and @pelson's ok, I'm not going to do anything anyways so I don't view not having permissions there as a problem. Though I guess with vacations and stuff it is good to have someone be able to steer the ship. 🚢 

However, this repo is becoming more important as we are moving obvious-ci here (discussed with @pelson already and it's in the notes). I know a fair bit about docker so imagine I will spend a good amount of time here. So, having permissions here is important.

**Comment by jakirkham** [comment]
Thanks for changing them, @ocefpaf.

**Comment by ocefpaf** [comment]
> Thanks for changing them, @ocefpaf.

Gotta make myself useful here :wink:

**Comment by jakirkham** [comment]
You've made yourself plenty useful. Don't worry about that.

**Comment by jakirkham** [comment]
Apparently the same typo is in the repo description, but I can't seem to edit it.

**Comment by jakirkham** [comment]
Thanks for fixing that.

**Comment by ocefpaf** [comment]
> Thanks for fixing that.

I am always confused about GitHub permission/teams. I just bumped you to `Admin` here and now I guess you can do that too.

**Comment by jakirkham** [comment]
> I am always confused about GitHub permission/teams. I just bumped you to Admin here and now I guess you can do that too.

No worries. Yep, it seems I can now.

**Pull request merged**
