### PR TITLE
update cuda 11.2 to 11.2.1

### PR DESCRIPTION
**Pull request by jaimergp**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jaimergp** [comment]
@conda-forge-admin, please rerender

**Comment by jaimergp** [comment]
CUDA 11.2.1 images [not yet available](https://hub.docker.com/r/nvidia/cuda/tags?page=1&ordering=last_updated&name=11.2.1).

**Comment by jakirkham** [comment]
They don't include minor versions in tags. So I don't think we need to do anything here. I believe they will just put this patch release in the existing 11.2 image (if that hasn't already happened)

**Comment by jaimergp** [comment]
Are you sure? I can see [`11.2.0` images](https://hub.docker.com/r/nvidia/cuda/tags?page=1&ordering=last_updated&name=11.2)...

**Comment by jaimergp** [comment]
I believe this is what @mike-wendt had to address for #171

**Comment by jakirkham** [comment]
> Are you sure? I can see [`11.2.0` images](https://hub.docker.com/r/nvidia/cuda/tags?page=1&ordering=last_updated&name=11.2)...

I guess not 😂

**Comment by jakirkham** [comment]
That said, I'm curious how much the image version matters for us given we are using the `cudatoolkit` package to supply libraries and the API shouldn't be changing between minor versions

**Comment by jaimergp** [comment]
11.2.1 images are now available, apparently! Retrying.

**Comment by jaimergp** [comment]
> I'm curious how much the image version matters for us

I'd say that given we have _not_ yet deployed the CUDA 11.1 and 11.2 migrator, there's no harm in getting the last version just in case we could run into weird corner cases. It'd be a different story if we had to rebuild packages, but fortunately we don't!

This should be ready for review @jakirkham

**Comment by jaimergp** [comment]
Anything else needed here @conda-forge/core?

**Review by kkraus14 — APPROVED** [review]
lgtm

**Comment by jakirkham** [comment]
Thanks Jaime! 😄

**Pull request merged**
