### PR TITLE
Add zip and unzip

### PR DESCRIPTION
**Pull request by jakirkham**
Fixes https://github.com/conda-forge/docker-images/issues/15

Adds `zip` and `unzip` to our docker image.

cc @jochym

### CODE REVIEW

**Comment by jakirkham** [comment]
Is it safe to assume that this is not controversial?

**Comment by pelson** [comment]
> Is it safe to assume that this is not controversial?

I'm bothered about turning the image into a general-purpose build utility - It would be useful to know if a package depends on libz rather than have it pulled in automatically.

**Comment by jjhelmus** [comment]
libz is not the same as zip and unzip, the former of which are similar to the tar utility.  I would be alright with this change but have no issue if these tools need to be explicitly included in the `yum_requirements.txt` file of a recipe.

**Comment by jakirkham** [comment]
Yeah, no preference from me. Figured it wasn't a big deal as we already include things like `tar`, `bzip2` and `patch`.

Was doing this mainly in response to issue ( https://github.com/conda-forge/docker-images/issues/15 ). Though I have forgotten what the problem was and whether it persisted. I thought we were able to build using . I'm pretty sure `conda-build` unzips and untars things with Python, right?

**Comment by ocefpaf** [comment]
> libz is not the same as zip and unzip, the former of which are similar to the tar utility. 

The problem is that sometimes an utility installs a lib and that may bring grieve later on.  `yum`, for example -- and a utility we do need BTW, needs `libxml` and that results in missing symbols in our packages.

**Comment by jakirkham** [comment]
Based on that logic there is a good argument for removing things like `bzip2` and the system `gcc` ( https://github.com/conda-forge/docker-images/pull/32 ). I'm ok with that path as well. If we think `zip`/`unzip` would rock the boat, then I'm totally ok with closing this.

Really any decision on this PR is welcome after 3mos. 😜

**Comment by pelson** [comment]
3 months and we haven't got a crying need for it. I'm closing until we do. More than happy for this to be reopened when we have a compelling operational conda-forge usecase.

Thanks all.

**Comment by jakirkham** [comment]
Speaking of things we don't have a need for. Please see PR ( https://github.com/conda-forge/docker-images/pull/32 ).

**Pull request closed without merging**
