### PR TITLE
Bump to Python 3.8

### PR DESCRIPTION
**Pull request by jakirkham**
Updates the Docker images to use Python 3.8.

cc @conda-forge/core

### CODE REVIEW

**Comment by jakirkham** [comment]
The `linux-anvil-armv7l` fails with the following. Could someone please advise?

```
PackagesNotFoundError: The following packages are not available from current channels:
1949
1950  - python=3.8
1951
1952Current channels:
1953
1954  - https://conda.anaconda.org/conda-forge/linux-armv7l
1955  - https://conda.anaconda.org/conda-forge/noarch
1956  - https://conda.anaconda.org/c4armv7l/linux-armv7l
1957  - https://conda.anaconda.org/c4armv7l/noarch
1958  - https://repo.anaconda.com/pkgs/main/linux-armv7l
1959  - https://repo.anaconda.com/pkgs/main/noarch
1960  - https://repo.anaconda.com/pkgs/r/linux-armv7l
1961  - https://repo.anaconda.com/pkgs/r/noarch
1962
1963To search for alternate channels that may provide the conda package you're
1964looking for, navigate to
1965
1966    https://anaconda.org
1967
1968and use the search bar at the top of the page.
```

https://travis-ci.com/github/conda-forge/docker-images/jobs/365822938

**Comment by jjhelmus** [comment]
No python 3.8 packages exist for linux-armv7l in any of the specified channels so the build fails.  Since we do not build packages for this platform in conda-forge it can be removed from the built matrix.

**Comment by jakirkham** [comment]
Thanks Jonathan! That makes sense to me. Submitted as PR ( https://github.com/conda-forge/docker-images/pull/145 ). Let's see what people think 🙂

**Comment by jakirkham** [comment]
Will be handled by the Miniforge update ( https://github.com/conda-forge/miniforge/pull/50 ).

**Comment by jakirkham** [comment]
Handling by upgrading to a newer version of Miniforge, which includes Python 3.8 ( https://github.com/conda-forge/docker-images/pull/156 ).

**Pull request closed without merging**
