### PR TITLE
Update CUDA 11.2 image to 11.2.2

### PR DESCRIPTION
**Pull request by jakirkham**
xref: https://github.com/conda-forge/cudatoolkit-feedstock/pull/57#issuecomment-804063842

cc @mike-wendt @kkraus14 @jaimergp @leofang

### CODE REVIEW

**Comment by jakirkham** [comment]
This may present an issue...

```
Step 3/28 : FROM nvidia/cuda:${CUDA_VER}-devel-centos${CENTOS_VER}
19
manifest for nvidia/cuda:11.2.2-devel-centos7 not found: manifest unknown: manifest unknown
```

https://github.com/conda-forge/docker-images/pull/177/checks?check_run_id=2169802842#step:6:18

**Comment by jakirkham** [comment]
Looks like we are waiting on upstream issue ( https://gitlab.com/nvidia/container-images/cuda/-/issues/115 ) to be resolved

**Comment by jakirkham** [comment]
Alright the upstream image is now available, but the image here won't build because we need the `cudatoolkit` package with the same version

**Comment by jaimergp** [comment]
Oops, you are right, we need to cache the package here. Then we need to merge https://github.com/conda-forge/cudatoolkit-feedstock/pull/57 and then this one.

**Comment by jakirkham** [comment]
Restarting CI now that `cudatoolkit` packages are published

**Comment by jakirkham** [comment]
New images are now deployed

**Pull request merged**
