### PR TITLE
Install Xvfb

### PR DESCRIPTION
**Pull request by jschueller**
Could be needed to run gui tests:
https://github.com/conda-forge/staged-recipes/pull/1684

### CODE REVIEW

**Comment by jakirkham** [comment]
Why not just use `yum_requirements.txt`?

**Comment by jakirkham** [comment]
Please see this [recipe]( https://github.com/conda-forge/qtconsole-feedstock/tree/421859b54e7ead2c2193971aefda86c8e55dbc57/recipe ) as an example.

**Comment by jschueller** [comment]
I did not know that.

**Comment by jakirkham** [comment]
No worries. FWIW I'm not saying this shouldn't be here. Just saying that if there is something not here that would be the thing to try first.

**Pull request closed without merging**
