### PR TITLE
WIP: Add CUDA and cuDNN

### PR DESCRIPTION
**Pull request by jakirkham**
Adds a docker image with CUDA and cuDNN. This is being done for CUDA as it is difficult to redistribute correctly. As far as cuDNN, we are not allowed to redistribute it; however, we are allowed to use their docker image this includes it. More discussion can be seen in this issue ( https://github.com/conda-forge/staged-recipes/issues/654 ). Please share thoughts and feedback on this potential solution.

cc @msarahan @lebedov

### CODE REVIEW

**Comment by msarahan** [comment]
This is a good thing but I still want a rock-solid,  possibly written
agreement with Nvidia on this usage.

**Comment by jakirkham** [comment]
Sure that sounds reasonable. Though I think you are in a better position to get that sort of thing.

**Comment by kyleabeauchamp** [comment]
For the sake of my own curiosity, is there any update on the CUDA support?

**Comment by jakirkham** [comment]
I have been meaning to raise that in a meeting for weeks. It seems that @msarahan and I keep missing each other. Also it has been lower on the stack with `conda-build` 2 and now Travis VM changes. Maybe try to revisit it in like a month. Will try to ping some people in the interim.

**Comment by jakirkham** [comment]
Closing out as PR ( https://github.com/conda-forge/docker-images/pull/93 ) supersedes this PR.

**Pull request closed without merging**
